@include ('templates.formularios.input', ['input' => 'cpf', 'attributes' => ['placeholder' => 'CPF']])
@include ('templates.formularios.input', ['input' => 'name', 'attributes' => ['placeholder' => 'Nome']])
@include ('templates.formularios.input', ['input' => 'phone', 'attributes' => ['placeholder' => 'Telefone']])
@include ('templates.formularios.input', ['input' => 'email', 'attributes' => ['placeholder' => 'Email']])
@include ('templates.formularios.password', ['input' => 'password', 'attributes' => ['placeholder' => 'Senha']])